language: c

os:
  - osx

compiler:
  - gcc

addons:
  homebrew:
    packages:
      - beanstalk

before_install:
  - brew update
  - python --version
  - ./install_mkdocs.sh

script:
  - python test.py
